version: "3.9"

services:
  productoService:
    container_name: ms-producto
    image: ms-producto:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - network_tp

networks:
  network_tp:
    driver: bridge