INSERT INTO prd_unidad (DESCRIPCION) VALUES ('kg');
INSERT INTO prd_unidad (DESCRIPCION) VALUES ('m3');
INSERT INTO prd_unidad (DESCRIPCION) VALUES ('m2');
INSERT INTO prd_unidad (DESCRIPCION) VALUES ('l');
INSERT INTO prd_unidad (DESCRIPCION) VALUES ('bolsas');